version: 2

references:
  node: &node
    docker:
      - image: circleci/node:10-stretch

  cf_install: &cf_install
    run:
      command: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
        mkdir -p `pwd`/bin
        chmod +x ./cf
        mv ./cf bin/
        echo export PATH="$PWD/bin:\$PATH" >> $BASH_ENV
        source $BASH_ENV
        cf install-plugin -f https://github.com/contraband/autopilot/releases/download/0.0.6/autopilot-linux

  cf_login: &cf_login
    run:
      command: |
        CF_USERNAME="${CF_Y_USER}" \
        CF_PASSWORD="${CF_Y_PASSWORD}" \
          make cf-login

  master_branch: &master_branch
    filters:
      branches:
        only:
          - master

  not_master_branch: &not_master_branch
    filters:
      branches:
        ignore:
          - master

jobs:
  setup-and-build:
    <<: *node
    steps:
        - checkout
        - *cf_install
        - run: make setup
        - run: make -j build
        - persist_to_workspace:
            root: .
            paths:
              - directory
              - example
  deploy-dev:
    <<: *node
    steps:
        - attach_workspace:
            at: .
        - *cf_login
        - run: make -j deploy
  deploy-prod:
    <<: *node
    steps:
        - attach_workspace:
            at: .
        - *cf_login
        - run: make -j deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup-and-build
      - deploy-dev:
          <<: *not_master_branch
          requires:
            - setup-and-build
      - unlock-prod-deploy:
          <<: *master_branch
          type: approval
          requires:
            - setup-and-build
      - deploy-prod:
          <<: *master_branch
          requires:
            - unlock-prod-deploy
